Document -Xverify:none to work around VerifyError
imagej/imagej.github.io pull request #224
Opened 2022-03-21 16:46 UTC by mkitti

This documents how to work around `java.lang.VerifyError: Expecting a stack map frame` when insert a Java 8 compiled ImageJ1 into FIJI as reported here and on image.sc:
https://github.com/imagej/ij1-patcher/issues/50

Also documentation is added on the use of ImageJ.cfg, replacing prior references to jvm.cfg.

2022-03-21 19:31 UTC, ctrueden requested changes
Thanks, @mkitti! Could you please confirm that the new instructions work as described, on both Windows and non-Windows systems? If you need additional testers for particular platforms, just say so here or in the chat, and others can help as well.

2022-03-21 19:41 UTC, imagejan commented on _pages/learn/launcher.md
> +- By modifying/creating the file `ImageJ.cfg` in the same directory as the ImageJ launcher.
From https://github.com/imagej/imagej-launcher/blob/a1b5432d6601690faca4e0aa196201e1f69d7f19/src/main/c/config.c#L186-L208, it seems that `ImageJ.cfg` is parsed *if* it exists, and `jvm.cfg` is only used as a fallback, if no `ImageJ.cfg` is present?

2022-03-22 03:58 UTC, ctrueden commented on _pages/learn/launcher.md
> +- By modifying/creating the file `ImageJ.cfg` in the same directory as the ImageJ launcher.
OK, thanks @imagejan. It seems we should change the docs as @mkitti has done here, then.

2022-03-22 04:43 UTC, mkitti commented on _pages/learn/launcher.md
> +- By modifying/creating the file `ImageJ.cfg` in the same directory as the ImageJ launcher.
I will test it shortly just to be sure, but yes, I was going off the source code in this case.

2022-03-22 05:10 UTC, mkitti commented on _pages/learn/launcher.md
> +- By modifying/creating the file `ImageJ.cfg` in the same directory as the ImageJ launcher.
This looks like the originating ticket:
https://imagej.net/tickets/1079.html

2022-03-22 16:27 UTC, merged